//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7DaysServerManager.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_7DaysServerManager.lang.lang_en", typeof(lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string _language_name {
            get {
                return ResourceManager.GetString("_language_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sean Davis.
        /// </summary>
        public static string _translation_author {
            get {
                return ResourceManager.GetString("_translation_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air drop frequency.
        /// </summary>
        public static string AirDropFrequency {
            get {
                return ResourceManager.GetString("AirDropFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string always_on_top {
            get {
                return ResourceManager.GetString("always_on_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        public static string ankieta {
            get {
                return ResourceManager.GetString("ankieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! Could you fill in the questionnaire? It it will not take more than a minute:).
        /// </summary>
        public static string ankieta_ask {
            get {
                return ResourceManager.GetString("ankieta_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m very very bad person. Don&apos;t ask me again..
        /// </summary>
        public static string ankieta_nie {
            get {
                return ResourceManager.GetString("ankieta_nie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll do it later.
        /// </summary>
        public static string ankieta_potem {
            get {
                return ResourceManager.GetString("ankieta_potem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure! Let&apos;s do this!:).
        /// </summary>
        public static string ankieta_tak {
            get {
                return ResourceManager.GetString("ankieta_tak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send anonymous usage statistics.
        /// </summary>
        public static string anon_data {
            get {
                return ResourceManager.GetString("anon_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are these?.
        /// </summary>
        public static string anon_data_2 {
            get {
                return ResourceManager.GetString("anon_data_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -OS Version,
        ///-If server is available on public servers list, server IP (for me only- so I can enter and play with you;))
        ///-If you are using built in website
        ///-If you are using Android widget
        ///
        ///All data is collected for statistics purpose only.
        ///
        ///If you don&apos;t allow to collect data, You&apos;re only added to total 7DSM runs counter..
        /// </summary>
        public static string anon_data_info {
            get {
                return ResourceManager.GetString("anon_data_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELED.
        /// </summary>
        public static string anul {
            get {
                return ResourceManager.GetString("anul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string anuluj {
            get {
                return ResourceManager.GetString("anuluj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect automatically.
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto backup.
        /// </summary>
        public static string auto_backup_check {
            get {
                return ResourceManager.GetString("auto_backup_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto command in:.
        /// </summary>
        public static string auto_messages_label {
            get {
                return ResourceManager.GetString("auto_messages_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn.
        /// </summary>
        public static string autobots {
            get {
                return ResourceManager.GetString("autobots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send chat message after creating backup.
        /// </summary>
        public static string backup_chat {
            get {
                return ResourceManager.GetString("backup_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting backup:.
        /// </summary>
        public static string backup_msg_1_l {
            get {
                return ResourceManager.GetString("backup_msg_1_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup complete:.
        /// </summary>
        public static string backup_msg_2_l {
            get {
                return ResourceManager.GetString("backup_msg_2_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup every.
        /// </summary>
        public static string backup_time {
            get {
                return ResourceManager.GetString("backup_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next backup in:.
        /// </summary>
        public static string backup_timer_label {
            get {
                return ResourceManager.GetString("backup_timer_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAN.
        /// </summary>
        public static string ban {
            get {
                return ResourceManager.GetString("ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to ban .
        /// </summary>
        public static string ban_sure {
            get {
                return ResourceManager.GetString("ban_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is banned now..
        /// </summary>
        public static string banned {
            get {
                return ResourceManager.GetString("banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAN.
        /// </summary>
        public static string bantime_slider {
            get {
                return ResourceManager.GetString("bantime_slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report bug.
        /// </summary>
        public static string blad {
            get {
                return ResourceManager.GetString("blad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block durability modifier.
        /// </summary>
        public static string block_durability_modifier_group {
            get {
                return ResourceManager.GetString("block_durability_modifier_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random box in:.
        /// </summary>
        public static string box_spawn_label {
            get {
                return ResourceManager.GetString("box_spawn_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box spawn delay.
        /// </summary>
        public static string box_spawn_time {
            get {
                return ResourceManager.GetString("box_spawn_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string canceled {
            get {
                return ResourceManager.GetString("canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Backup system]Creating backup....
        /// </summary>
        public static string chat_backup_1 {
            get {
                return ResourceManager.GetString("chat_backup_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Backup system]Backup created..
        /// </summary>
        public static string chat_backup_2 {
            get {
                return ResourceManager.GetString("chat_backup_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string chat_g {
            get {
                return ResourceManager.GetString("chat_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat Mode.
        /// </summary>
        public static string cheatmode {
            get {
                return ResourceManager.GetString("cheatmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string chpath {
            get {
                return ResourceManager.GetString("chpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Exit (if unchecked SM will NOT kill server on exit!).
        /// </summary>
        public static string cleanexit {
            get {
                return ResourceManager.GetString("cleanexit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close server.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing server....
        /// </summary>
        public static string closing {
            get {
                return ResourceManager.GetString("closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait %d minutes before using this command again..
        /// </summary>
        public static string cmd_not_yet {
            get {
                return ResourceManager.GetString("cmd_not_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use command yet (%d = time left):.
        /// </summary>
        public static string cmd_not_yet_l {
            get {
                return ResourceManager.GetString("cmd_not_yet_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server main config file.
        /// </summary>
        public static string configfile_g {
            get {
                return ResourceManager.GetString("configfile_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string cpl_pass {
            get {
                return ResourceManager.GetString("cpl_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string cpl_port {
            get {
                return ResourceManager.GetString("cpl_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server crashed... Restarting....
        /// </summary>
        public static string crash {
            get {
                return ResourceManager.GetString("crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant.
        /// </summary>
        public static string ctime_0 {
            get {
                return ResourceManager.GetString("ctime_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ctime_1 {
            get {
                return ResourceManager.GetString("ctime_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string ctime_2 {
            get {
                return ResourceManager.GetString("ctime_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft timer / Loot timer.
        /// </summary>
        public static string ctime_g {
            get {
                return ResourceManager.GetString("ctime_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWW Control panel.
        /// </summary>
        public static string ctrlp {
            get {
                return ResourceManager.GetString("ctrlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWW Control panel.
        /// </summary>
        public static string ctrlpanel {
            get {
                return ResourceManager.GetString("ctrlpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom commands.
        /// </summary>
        public static string customcommands_g {
            get {
                return ResourceManager.GetString("customcommands_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is random: 5min-2h.
        /// </summary>
        public static string czasinfo {
            get {
                return ResourceManager.GetString("czasinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir seems to be all right. Saved.
        /// </summary>
        public static string dir_ok {
            get {
                return ResourceManager.GetString("dir_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day length.
        /// </summary>
        public static string dlugoscdnia {
            get {
                return ResourceManager.GetString("dlugoscdnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        public static string dod_0 {
            get {
                return ResourceManager.GetString("dod_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbelt.
        /// </summary>
        public static string dod_1 {
            get {
                return ResourceManager.GetString("dod_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpack.
        /// </summary>
        public static string dod_2 {
            get {
                return ResourceManager.GetString("dod_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string dod_3 {
            get {
                return ResourceManager.GetString("dod_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop on death / Drop on quit.
        /// </summary>
        public static string dod_g {
            get {
                return ResourceManager.GetString("dod_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string doq_0 {
            get {
                return ResourceManager.GetString("doq_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        public static string doq_1 {
            get {
                return ResourceManager.GetString("doq_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbelt.
        /// </summary>
        public static string doq_2 {
            get {
                return ResourceManager.GetString("doq_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpack.
        /// </summary>
        public static string doq_3 {
            get {
                return ResourceManager.GetString("doq_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop on quit.
        /// </summary>
        public static string doq_g {
            get {
                return ResourceManager.GetString("doq_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers list and server password.
        /// </summary>
        public static string dostep {
            get {
                return ResourceManager.GetString("dostep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string dzien {
            get {
                return ResourceManager.GetString("dzien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom commands.
        /// </summary>
        public static string enable_cc {
            get {
                return ResourceManager.GetString("enable_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove server_updater.exe. Remove it manually..
        /// </summary>
        public static string err_su_rem {
            get {
                return ResourceManager.GetString("err_su_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy sense memory.
        /// </summary>
        public static string esm_g {
            get {
                return ResourceManager.GetString("esm_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic spawning mode.
        /// </summary>
        public static string espawnmode_g {
            get {
                return ResourceManager.GetString("espawnmode_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponential.
        /// </summary>
        public static string Exponential {
            get {
                return ResourceManager.GetString("Exponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Like us on facebook!.
        /// </summary>
        public static string fb_label {
            get {
                return ResourceManager.GetString("fb_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feral difficulty.
        /// </summary>
        public static string feral {
            get {
                return ResourceManager.GetString("feral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server admin config file.
        /// </summary>
        public static string filename_g {
            get {
                return ResourceManager.GetString("filename_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to show path of game dir. If you&apos;re using Steam version use &quot;Detect automatically&quot;, otherwise select &quot;I&apos;ll show path manually&quot;..
        /// </summary>
        public static string fr_detect {
            get {
                return ResourceManager.GetString("fr_detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s all. Click &quot;Finish&quot; to return to profiles menu..
        /// </summary>
        public static string fr_end {
            get {
                return ResourceManager.GetString("fr_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string fr_fin {
            get {
                return ResourceManager.GetString("fr_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create new profile, enter its name in the field below..
        /// </summary>
        public static string fr_hi {
            get {
                return ResourceManager.GetString("fr_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frag limit.
        /// </summary>
        public static string fraglimit {
            get {
                return ResourceManager.GetString("fraglimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly fire.
        /// </summary>
        public static string friendlyfire {
            get {
                return ResourceManager.GetString("friendlyfire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full protection until claim is expired.
        /// </summary>
        public static string Full_prot {
            get {
                return ResourceManager.GetString("Full_prot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game files not found..
        /// </summary>
        public static string game_not_found {
            get {
                return ResourceManager.GetString("game_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game files not found..
        /// </summary>
        public static string game_not_found_2 {
            get {
                return ResourceManager.GetString("game_not_found_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7DaysToDie.exe not found!.
        /// </summary>
        public static string game_not_found_cons {
            get {
                return ResourceManager.GetString("game_not_found_cons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival SP.
        /// </summary>
        public static string gamemode_coop {
            get {
                return ResourceManager.GetString("gamemode_coop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombie horde.
        /// </summary>
        public static string gamemode_horda {
            get {
                return ResourceManager.GetString("gamemode_horda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathmatch.
        /// </summary>
        public static string gamemode_pvp {
            get {
                return ResourceManager.GetString("gamemode_pvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string godzina {
            get {
                return ResourceManager.GetString("godzina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string graczegroup {
            get {
                return ResourceManager.GetString("graczegroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string grout_server_telnet {
            get {
                return ResourceManager.GetString("grout_server_telnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to create commands?.
        /// </summary>
        public static string how_to_commands {
            get {
                return ResourceManager.GetString("how_to_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string iloscdni {
            get {
                return ResourceManager.GetString("iloscdni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m here!.
        /// </summary>
        public static string imhere {
            get {
                return ResourceManager.GetString("imhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KICK.
        /// </summary>
        public static string kick {
            get {
                return ResourceManager.GetString("kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been kicked..
        /// </summary>
        public static string kick_ok {
            get {
                return ResourceManager.GetString("kick_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KICK.
        /// </summary>
        public static string kickgroup {
            get {
                return ResourceManager.GetString("kickgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?
        ///This may corrupt your save file!.
        /// </summary>
        public static string kill_click {
            get {
                return ResourceManager.GetString("kill_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill proccess.
        /// </summary>
        public static string kill_proccess {
            get {
                return ResourceManager.GetString("kill_proccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers closing error. It shouldn&apos;t be a problem, but if something in not ok try restarting SM.
        ///
        ///.
        /// </summary>
        public static string kill_workers_err {
            get {
                return ResourceManager.GetString("kill_workers_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing proccess....
        /// </summary>
        public static string killing_proc {
            get {
                return ResourceManager.GetString("killing_proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string kons_group {
            get {
                return ResourceManager.GetString("kons_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string kontrola {
            get {
                return ResourceManager.GetString("kontrola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claiming land.
        /// </summary>
        public static string LandClaim {
            get {
                return ResourceManager.GetString("LandClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land claim durability modifier.
        /// </summary>
        public static string LandClaim_g {
            get {
                return ResourceManager.GetString("LandClaim_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land claim dead zone.
        /// </summary>
        public static string LandClaimDeadZone_g {
            get {
                return ResourceManager.GetString("LandClaimDeadZone_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land claim decay node.
        /// </summary>
        public static string LandClaimDecayMode_g {
            get {
                return ResourceManager.GetString("LandClaimDecayMode_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land claim expiry time.
        /// </summary>
        public static string LandClaimExpiryTime_g {
            get {
                return ResourceManager.GetString("LandClaimExpiryTime_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land claim size.
        /// </summary>
        public static string LandClaimSize_g {
            get {
                return ResourceManager.GetString("LandClaimSize_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lang_g {
            get {
                return ResourceManager.GetString("lang_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string Linear {
            get {
                return ResourceManager.GetString("Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot abundance.
        /// </summary>
        public static string LootAbundance_g {
            get {
                return ResourceManager.GetString("LootAbundance_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot respawn days.
        /// </summary>
        public static string LootRespawnDays_g {
            get {
                return ResourceManager.GetString("LootRespawnDays_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant.
        /// </summary>
        public static string ltime_0 {
            get {
                return ResourceManager.GetString("ltime_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ltime_1 {
            get {
                return ResourceManager.GetString("ltime_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string ltime_2 {
            get {
                return ResourceManager.GetString("ltime_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot timer.
        /// </summary>
        public static string ltime_g {
            get {
                return ResourceManager.GetString("ltime_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll show path manually.
        /// </summary>
        public static string manual {
            get {
                return ResourceManager.GetString("manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match length.
        /// </summary>
        public static string matchlength {
            get {
                return ResourceManager.GetString("matchlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max players.
        /// </summary>
        public static string maxplgroup {
            get {
                return ResourceManager.GetString("maxplgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max spawned animals.
        /// </summary>
        public static string MaxSpawnedAnimals_g {
            get {
                return ResourceManager.GetString("MaxSpawnedAnimals_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max spawned zombies.
        /// </summary>
        public static string MaxSpawnedZombies_g {
            get {
                return ResourceManager.GetString("MaxSpawnedZombies_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server chat messages.
        /// </summary>
        public static string messages_g {
            get {
                return ResourceManager.GetString("messages_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off NAT (try it if nobody can enter the server).
        /// </summary>
        public static string nat {
            get {
                return ResourceManager.GetString("nat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game name, server name and map.
        /// </summary>
        public static string nazwamapa {
            get {
                return ResourceManager.GetString("nazwamapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near player:.
        /// </summary>
        public static string near_label {
            get {
                return ResourceManager.GetString("near_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Light Length.
        /// </summary>
        public static string nightpercentage_g {
            get {
                return ResourceManager.GetString("nightpercentage_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not connected to server. I cannot do that..
        /// </summary>
        public static string no_con {
            get {
                return ResourceManager.GetString("no_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no players on the server..
        /// </summary>
        public static string no_pl {
            get {
                return ResourceManager.GetString("no_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter profile name..
        /// </summary>
        public static string no_prof_name {
            get {
                return ResourceManager.GetString("no_prof_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string odery {
            get {
                return ResourceManager.GetString("odery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string offline {
            get {
                return ResourceManager.GetString("offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player damage given.
        /// </summary>
        public static string p_dmg_g_g {
            get {
                return ResourceManager.GetString("p_dmg_g_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player damage recieved.
        /// </summary>
        public static string p_dmg_r_g {
            get {
                return ResourceManager.GetString("p_dmg_r_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game files path: .
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent player profiles.
        /// </summary>
        public static string PersistentPlayerProfiles {
            get {
                return ResourceManager.GetString("PersistentPlayerProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server port.
        /// </summary>
        public static string port_g {
            get {
                return ResourceManager.GetString("port_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMED.
        /// </summary>
        public static string potw {
            get {
                return ResourceManager.GetString("potw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string powod {
            get {
                return ResourceManager.GetString("powod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proccess killed.
        /// </summary>
        public static string proc_killed {
            get {
                return ResourceManager.GetString("proc_killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random.
        /// </summary>
        public static string random {
            get {
                return ResourceManager.GetString("random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize game clock with real one (resets days counter!).
        /// </summary>
        public static string realtime {
            get {
                return ResourceManager.GetString("realtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to running server.
        /// </summary>
        public static string reboot_con {
            get {
                return ResourceManager.GetString("reboot_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot now:.
        /// </summary>
        public static string reboot_l {
            get {
                return ResourceManager.GetString("reboot_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left to reboot (%d = time left):.
        /// </summary>
        public static string reboot_time_l {
            get {
                return ResourceManager.GetString("reboot_time_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is restarting NOW..
        /// </summary>
        public static string rebooting {
            get {
                return ResourceManager.GetString("rebooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild map after match.
        /// </summary>
        public static string rebuildmap {
            get {
                return ResourceManager.GetString("rebuildmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reestablishing connection to 7DTD server....
        /// </summary>
        public static string rees {
            get {
                return ResourceManager.GetString("rees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download playerlist..
        /// </summary>
        public static string ref_err {
            get {
                return ResourceManager.GetString("ref_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh player list.
        /// </summary>
        public static string refresh_players {
            get {
                return ResourceManager.GetString("refresh_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control Panel.
        /// </summary>
        public static string remote_cpl {
            get {
                return ResourceManager.GetString("remote_cpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control enabled.
        /// </summary>
        public static string remote_enable {
            get {
                return ResourceManager.GetString("remote_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Management.
        /// </summary>
        public static string remote_g {
            get {
                return ResourceManager.GetString("remote_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an account!.
        /// </summary>
        public static string remote_get {
            get {
                return ResourceManager.GetString("remote_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong login or password... Disabled remote control..
        /// </summary>
        public static string remote_login_error {
            get {
                return ResourceManager.GetString("remote_login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control Login:.
        /// </summary>
        public static string remote_login_l {
            get {
                return ResourceManager.GetString("remote_login_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected....
        /// </summary>
        public static string remote_ok {
            get {
                return ResourceManager.GetString("remote_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control Password:.
        /// </summary>
        public static string remote_password_l {
            get {
                return ResourceManager.GetString("remote_password_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote server:.
        /// </summary>
        public static string remote_server_l {
            get {
                return ResourceManager.GetString("remote_server_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string remote_waiting {
            get {
                return ResourceManager.GetString("remote_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn players before restart.
        /// </summary>
        public static string reset_chat {
            get {
                return ResourceManager.GetString("reset_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto restarts.
        /// </summary>
        public static string reset_enabled {
            get {
                return ResourceManager.GetString("reset_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto restarts.
        /// </summary>
        public static string reset_g {
            get {
                return ResourceManager.GetString("reset_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server will restart in %d minutes..
        /// </summary>
        public static string reset_time_left {
            get {
                return ResourceManager.GetString("reset_time_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next auto restart in:.
        /// </summary>
        public static string reset_timer_label {
            get {
                return ResourceManager.GetString("reset_timer_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to restore manager..
        /// </summary>
        public static string restore {
            get {
                return ResourceManager.GetString("restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server running from path: .
        /// </summary>
        public static string run_from {
            get {
                return ResourceManager.GetString("run_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string sa_edit {
            get {
                return ResourceManager.GetString("sa_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saves dir. (leave empty to use default).
        /// </summary>
        public static string save_g {
            get {
                return ResourceManager.GetString("save_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save logs to files.
        /// </summary>
        public static string save_logfiles {
            get {
                return ResourceManager.GetString("save_logfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save logs to file.
        /// </summary>
        public static string save_logfiles_2 {
            get {
                return ResourceManager.GetString("save_logfiles_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ban time.
        /// </summary>
        public static string sel_ban_time {
            get {
                return ResourceManager.GetString("sel_ban_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select player from list..
        /// </summary>
        public static string select_player {
            get {
                return ResourceManager.GetString("select_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server closed.
        /// </summary>
        public static string server_closed {
            get {
                return ResourceManager.GetString("server_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Description.
        /// </summary>
        public static string ServerDescription_g {
            get {
                return ResourceManager.GetString("ServerDescription_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show server on servers list.
        /// </summary>
        public static string ServerIsPublic {
            get {
                return ResourceManager.GetString("ServerIsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Website URL.
        /// </summary>
        public static string ServerWebsiteURL_g {
            get {
                return ResourceManager.GetString("ServerWebsiteURL_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show IP.
        /// </summary>
        public static string show_ip {
            get {
                return ResourceManager.GetString("show_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Show these stats).
        /// </summary>
        public static string show_stats {
            get {
                return ResourceManager.GetString("show_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show players on map.
        /// </summary>
        public static string showonmap {
            get {
                return ResourceManager.GetString("showonmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random commands.
        /// </summary>
        public static string spam_g {
            get {
                return ResourceManager.GetString("spam_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &quot;say&quot; to every command..
        /// </summary>
        public static string spam_is_spam {
            get {
                return ResourceManager.GetString("spam_is_spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between commands.
        /// </summary>
        public static string spam_time {
            get {
                return ResourceManager.GetString("spam_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands written here will be send to server. Each command should be written in new line..
        /// </summary>
        public static string spaminfo {
            get {
                return ResourceManager.GetString("spaminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn random boxes near players.
        /// </summary>
        public static string spawn_box {
            get {
                return ResourceManager.GetString("spawn_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random boxes.
        /// </summary>
        public static string spawn_box_2 {
            get {
                return ResourceManager.GetString("spawn_box_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items spawning.
        /// </summary>
        public static string spawn_group {
            get {
                return ResourceManager.GetString("spawn_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn.
        /// </summary>
        public static string spawn_now {
            get {
                return ResourceManager.GetString("spawn_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn random zombies near players.
        /// </summary>
        public static string spawn_zombie {
            get {
                return ResourceManager.GetString("spawn_zombie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addonal random zombies.
        /// </summary>
        public static string spawn_zombie_2 {
            get {
                return ResourceManager.GetString("spawn_zombie_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Database.
        /// </summary>
        public static string sql_db_name_g {
            get {
                return ResourceManager.GetString("sql_db_name_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data to MySQL database.
        /// </summary>
        public static string sql_enabled {
            get {
                return ResourceManager.GetString("sql_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL export in:.
        /// </summary>
        public static string sql_export_label {
            get {
                return ResourceManager.GetString("sql_export_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server.
        /// </summary>
        public static string sql_host_g {
            get {
                return ResourceManager.GetString("sql_host_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Password.
        /// </summary>
        public static string sql_password_g {
            get {
                return ResourceManager.GetString("sql_password_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update every.
        /// </summary>
        public static string sql_updates_time_g {
            get {
                return ResourceManager.GetString("sql_updates_time_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Username.
        /// </summary>
        public static string sql_username_g {
            get {
                return ResourceManager.GetString("sql_username_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored password is NOT encrypted!.
        /// </summary>
        public static string sql_warn {
            get {
                return ResourceManager.GetString("sql_warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start server.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in: .
        /// </summary>
        public static string start_in {
            get {
                return ResourceManager.GetString("start_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status always shows that server is online when game is running..
        /// </summary>
        public static string status_info {
            get {
                return ResourceManager.GetString("status_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: OFFLINE.
        /// </summary>
        public static string status_not {
            get {
                return ResourceManager.GetString("status_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: ONLINE.
        /// </summary>
        public static string status_working {
            get {
                return ResourceManager.GetString("status_working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t found game on Steam. You have to download the game via Steam..
        /// </summary>
        public static string steam_no_game {
            get {
                return ResourceManager.GetString("steam_no_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam not found. Set path manually.
        /// </summary>
        public static string steam_no_steam {
            get {
                return ResourceManager.GetString("steam_no_steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found game files. Should work:).
        /// </summary>
        public static string steam_ok {
            get {
                return ResourceManager.GetString("steam_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect From Steam.
        /// </summary>
        public static string steamsearch {
            get {
                return ResourceManager.GetString("steamsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went terribly wrong. Restart server..
        /// </summary>
        public static string sth_went_terribly_wrong {
            get {
                return ResourceManager.GetString("sth_went_terribly_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown server.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to turn the server off?.
        /// </summary>
        public static string sure_close {
            get {
                return ResourceManager.GetString("sure_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server broke telnet connection!.
        /// </summary>
        public static string telnet_broken {
            get {
                return ResourceManager.GetString("telnet_broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string telnet_connect {
            get {
                return ResourceManager.GetString("telnet_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telnet connection.
        /// </summary>
        public static string telnet_g {
            get {
                return ResourceManager.GetString("telnet_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game time.
        /// </summary>
        public static string telnet_group {
            get {
                return ResourceManager.GetString("telnet_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server refused connection.
        ///
        ///
        ///
        ///.
        /// </summary>
        public static string telnet_refuse {
            get {
                return ResourceManager.GetString("telnet_refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers.
        /// </summary>
        public static string timers_g {
            get {
                return ResourceManager.GetString("timers_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for game.
        /// </summary>
        public static string title_ver {
            get {
                return ResourceManager.GetString("title_ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalize to tray.
        /// </summary>
        public static string to_tray {
            get {
                return ResourceManager.GetString("to_tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for translation to your language.
        /// </summary>
        public static string translate {
            get {
                return ResourceManager.GetString("translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or create your own translation.
        /// </summary>
        public static string translate_2 {
            get {
                return ResourceManager.GetString("translate_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string trudnoscgroup {
            get {
                return ResourceManager.GetString("trudnoscgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamemode.
        /// </summary>
        public static string trybgry {
            get {
                return ResourceManager.GetString("trybgry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item/mob.
        /// </summary>
        public static string typ {
            get {
                return ResourceManager.GetString("typ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available!.
        /// </summary>
        public static string upd_ava {
            get {
                return ResourceManager.GetString("upd_ava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available! Download now?.
        /// </summary>
        public static string upd_ava_2 {
            get {
                return ResourceManager.GetString("upd_ava_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during connecting to update server: the server is down, your connection to the internet is down or you&apos;re using unregistered build (server doesn&apos;t know your version of 7DSM, so it can&apos;t tell you if there are updates for it)..
        /// </summary>
        public static string upd_err {
            get {
                return ResourceManager.GetString("upd_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secs. Don&apos;t update too often..
        /// </summary>
        public static string upd_time {
            get {
                return ResourceManager.GetString("upd_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful.
        /// </summary>
        public static string update_ok {
            get {
                return ResourceManager.GetString("update_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ustawienia_grupa_ustawienia {
            get {
                return ResourceManager.GetString("ustawienia_grupa_ustawienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Easy Anti Cheat.
        /// </summary>
        public static string VACEnabled {
            get {
                return ResourceManager.GetString("VACEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait....
        /// </summary>
        public static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window request.
        /// </summary>
        public static string wn_cl {
            get {
                return ResourceManager.GetString("wn_cl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running workers:.
        /// </summary>
        public static string workerynapis {
            get {
                return ResourceManager.GetString("workerynapis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saves directory is incorrect..
        /// </summary>
        public static string wrong_map_dir {
            get {
                return ResourceManager.GetString("wrong_map_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombies.
        /// </summary>
        public static string zomb_pie {
            get {
                return ResourceManager.GetString("zomb_pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombies never run.
        /// </summary>
        public static string zombie_never_run {
            get {
                return ResourceManager.GetString("zombie_never_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombies run at night.
        /// </summary>
        public static string zombie_normal {
            get {
                return ResourceManager.GetString("zombie_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombies always run.
        /// </summary>
        public static string zombie_run {
            get {
                return ResourceManager.GetString("zombie_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random zombie in:.
        /// </summary>
        public static string zombie_spawn_label {
            get {
                return ResourceManager.GetString("zombie_spawn_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombie spawn delay.
        /// </summary>
        public static string zombie_spawn_time {
            get {
                return ResourceManager.GetString("zombie_spawn_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic zombies spawn.
        /// </summary>
        public static string zombiespawn {
            get {
                return ResourceManager.GetString("zombiespawn", resourceCulture);
            }
        }
    }
}
